void serial_print_out()//串口输出函数
{
  Serial.print("tire=");
  Serial.print(tire_speed);
  Serial.print("per=");
  Serial.print(per_hour);
  Serial.print("unm=");
  Serial.print(unmanned);
  Serial.print("h_unm=");
  Serial.print(host_unmanned);
  Serial.println();
  Serial.print("tell_s=");
  Serial.print(tellurometer_survey);
  Serial.print("ob1=");
  Serial.print(obstacle_1);
  Serial.print("ob2=");
  Serial.print(obstacle_2);
  Serial.print("ob3=");
  Serial.print(obstacle_3);
  Serial.print("ob4=");
  Serial.print(obstacle_4);
  Serial.print("ob5=");
  Serial.print(obstacle_5);
  Serial.print("ob6=");
  Serial.print(obstacle_6);
  Serial.print("ob7=");
  Serial.print(obstacle_7);
  Serial.print("ob8=");
  Serial.print(obstacle_8);
  Serial.println();
  Serial.print("x=");
  Serial.print(ACC_x);
  Serial.print("y=");
  Serial.print(ACC_y);
  Serial.print("z=");
  Serial.print(ACC_z);
  Serial.println();
  delay(2);
}
